=== ngocpq/HCMUTE-Online-Judge/SPKTOnline/XML/ToeicScore.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ToeicScore (Score*)>
<!ELEMENT Score (CorrectNumber, ListeningScore, ReadingScore)>
<!ELEMENT CorrectNumber (#PCDATA)>
<!ELEMENT ListeningScore (#PCDATA)>
<!ELEMENT ReadingScore (#PCDATA)>

=== ngocpq/HCMUTE-Online-Judge/SPKTOnline/XML/ToeicScore.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ToeicScore SYSTEM "ToeicScore.dtd"[]>
<ToeicScore>

  <Score>
    <CorrectNumber>0</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>1</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>2</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>3</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>4</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>5</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>6</CorrectNumber>
    <ListeningScore>5</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>7</CorrectNumber>
    <ListeningScore>10</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>8</CorrectNumber>
    <ListeningScore>15</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>9</CorrectNumber>
    <ListeningScore>20</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>10</CorrectNumber>
    <ListeningScore>25</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>11</CorrectNumber>
    <ListeningScore>30</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>12</CorrectNumber>
    <ListeningScore>35</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>13</CorrectNumber>
    <ListeningScore>40</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>14</CorrectNumber>
    <ListeningScore>45</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>15</CorrectNumber>
    <ListeningScore>50</ListeningScore>
    <ReadingScore>5</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>16</CorrectNumber>
    <ListeningScore>55</ListeningScore>
    <ReadingScore>10</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>17</CorrectNumber>
    <ListeningScore>60</ListeningScore>
    <ReadingScore>15</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>18</CorrectNumber>
    <ListeningScore>65</ListeningScore>
    <ReadingScore>20</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>19</CorrectNumber>
    <ListeningScore>70</ListeningScore>
    <ReadingScore>25</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>20</CorrectNumber>
    <ListeningScore>75</ListeningScore>
    <ReadingScore>30</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>21</CorrectNumber>
    <ListeningScore>80</ListeningScore>
    <ReadingScore>35</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>22</CorrectNumber>
    <ListeningScore>85</ListeningScore>
    <ReadingScore>40</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>23</CorrectNumber>
    <ListeningScore>90</ListeningScore>
    <ReadingScore>45</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>24</CorrectNumber>
    <ListeningScore>95</ListeningScore>
    <ReadingScore>50</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>25</CorrectNumber>
    <ListeningScore>100</ListeningScore>
    <ReadingScore>60</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>26</CorrectNumber>
    <ListeningScore>110</ListeningScore>
    <ReadingScore>65</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>27</CorrectNumber>
    <ListeningScore>115</ListeningScore>
    <ReadingScore>70</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>28</CorrectNumber>
    <ListeningScore>120</ListeningScore>
    <ReadingScore>80</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>29</CorrectNumber>
    <ListeningScore>125</ListeningScore>
    <ReadingScore>85</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>30</CorrectNumber>
    <ListeningScore>130</ListeningScore>
    <ReadingScore>90</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>31</CorrectNumber>
    <ListeningScore>135</ListeningScore>
    <ReadingScore>95</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>32</CorrectNumber>
    <ListeningScore>140</ListeningScore>
    <ReadingScore>100</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>33</CorrectNumber>
    <ListeningScore>145</ListeningScore>
    <ReadingScore>110</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>34</CorrectNumber>
    <ListeningScore>150</ListeningScore>
    <ReadingScore>115</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>35</CorrectNumber>
    <ListeningScore>160</ListeningScore>
    <ReadingScore>120</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>36</CorrectNumber>
    <ListeningScore>165</ListeningScore>
    <ReadingScore>125</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>37</CorrectNumber>
    <ListeningScore>170</ListeningScore>
    <ReadingScore>130</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>38</CorrectNumber>
    <ListeningScore>175</ListeningScore>
    <ReadingScore>140</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>39</CorrectNumber>
    <ListeningScore>180</ListeningScore>
    <ReadingScore>145</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>40</CorrectNumber>
    <ListeningScore>185</ListeningScore>
    <ReadingScore>150</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>41</CorrectNumber>
    <ListeningScore>190</ListeningScore>
    <ReadingScore>160</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>42</CorrectNumber>
    <ListeningScore>195</ListeningScore>
    <ReadingScore>165</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>43</CorrectNumber>
    <ListeningScore>200</ListeningScore>
    <ReadingScore>170</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>44</CorrectNumber>
    <ListeningScore>210</ListeningScore>
    <ReadingScore>175</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>45</CorrectNumber>
    <ListeningScore>215</ListeningScore>
    <ReadingScore>180</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>46</CorrectNumber>
    <ListeningScore>220</ListeningScore>
    <ReadingScore>190</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>47</CorrectNumber>
    <ListeningScore>230</ListeningScore>
    <ReadingScore>195</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>48</CorrectNumber>
    <ListeningScore>240</ListeningScore>
    <ReadingScore>200</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>49</CorrectNumber>
    <ListeningScore>245</ListeningScore>
    <ReadingScore>210</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>50</CorrectNumber>
    <ListeningScore>250</ListeningScore>
    <ReadingScore>215</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>51</CorrectNumber>
    <ListeningScore>255</ListeningScore>
    <ReadingScore>220</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>52</CorrectNumber>
    <ListeningScore>260</ListeningScore>
    <ReadingScore>225</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>53</CorrectNumber>
    <ListeningScore>270</ListeningScore>
    <ReadingScore>230</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>54</CorrectNumber>
    <ListeningScore>275</ListeningScore>
    <ReadingScore>235</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>55</CorrectNumber>
    <ListeningScore>280</ListeningScore>
    <ReadingScore>240</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>56</CorrectNumber>
    <ListeningScore>290</ListeningScore>
    <ReadingScore>250</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>57</CorrectNumber>
    <ListeningScore>295</ListeningScore>
    <ReadingScore>255</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>58</CorrectNumber>
    <ListeningScore>300</ListeningScore>
    <ReadingScore>260</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>59</CorrectNumber>
    <ListeningScore>310</ListeningScore>
    <ReadingScore>265</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>60</CorrectNumber>
    <ListeningScore>315</ListeningScore>
    <ReadingScore>270</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>61</CorrectNumber>
    <ListeningScore>320</ListeningScore>
    <ReadingScore>280</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>62</CorrectNumber>
    <ListeningScore>325</ListeningScore>
    <ReadingScore>285</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>63</CorrectNumber>
    <ListeningScore>330</ListeningScore>
    <ReadingScore>290</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>64</CorrectNumber>
    <ListeningScore>340</ListeningScore>
    <ReadingScore>300</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>65</CorrectNumber>
    <ListeningScore>345</ListeningScore>
    <ReadingScore>305</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>66</CorrectNumber>
    <ListeningScore>350</ListeningScore>
    <ReadingScore>310</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>67</CorrectNumber>
    <ListeningScore>360</ListeningScore>
    <ReadingScore>320</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>68</CorrectNumber>
    <ListeningScore>365</ListeningScore>
    <ReadingScore>325</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>69</CorrectNumber>
    <ListeningScore>370</ListeningScore>
    <ReadingScore>330</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>70</CorrectNumber>
    <ListeningScore>380</ListeningScore>
    <ReadingScore>335</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>71</CorrectNumber>
    <ListeningScore>385</ListeningScore>
    <ReadingScore>340</ReadingScore>
  </Score>
  <Score>
    <CorrectNumber>72</CorrectNumber>
    <ListeningScore>390</ListeningScore>
